import type { SchemaObject } from '../node_modules/ajv/dist/ajv.js'

const id = { type: 'string', pattern: '^[a-z0-9]+(?:[.-][a-z0-9]+)*$' } as const
const sha256 = { type: 'string', pattern: '^[a-f0-9]{64}$' } as const
const sourceRefSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['sourceId', 'itemId', 'locatorDigest', 'valueDigest'],
  properties: { sourceId: id, itemId: id, locatorDigest: sha256, valueDigest: sha256 },
} as const
const sourceRefArray = {
  type: 'array',
  items: sourceRefSchema,
  minItems: 1,
  uniqueItems: true,
} as const
const nullableSourceRef = { anyOf: [sourceRefSchema, { type: 'null' }] } as const
const stringSet = (values: readonly string[]) => ({
  type: 'array',
  items: { enum: values },
  minItems: 1,
  uniqueItems: true,
})

const evidenceRefSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['kind', 'path', 'digest'],
  properties: {
    kind: {
      enum: ['predicate-contract', 'negative-test', 'corpus-sweep', 'independent-bypass'],
    },
    path: {
      type: 'string',
      minLength: 1,
      pattern: '^(?![A-Za-z]:)(?!/)(?!.*\\\\)(?!.*(?:^|/)\\.\\.(?:/|$))(?!.*[*?]).+$',
    },
    digest: sha256,
  },
} as const

export const authorityEnforcementRegistrySchema: SchemaObject = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'https://foreman-line.local/schemas/authority-enforcement-registry.schema.json',
  title: 'Foreman Kernel Authority and Enforcement Registry',
  type: 'object',
  additionalProperties: false,
  required: [
    'schemaVersion',
    'registryId',
    'sourceSnapshotCommit',
    'sources',
    'rules',
    'operationAuthority',
    'reconciliations',
  ],
  properties: {
    schemaVersion: { const: '0.1.0' },
    registryId: { const: 'foreman-kernel-authority-enforcement' },
    sourceSnapshotCommit: { type: 'string', pattern: '^[a-f0-9]{40}$' },
    sources: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'sourceId',
          'path',
          'sourceKind',
          'authorityTier',
          'authorityEffect',
          'scope',
          'snapshotEvidence',
          'inventoryItems',
        ],
        properties: {
          sourceId: id,
          path: { type: 'string', minLength: 1 },
          sourceKind: {
            enum: [
              'developer-ratification',
              'goal-charter',
              'foreman-contract',
              'coordinator-pattern',
              'parcel-spec',
              'standing-constraint',
              'live-implementation',
              'historical',
              'generated-advisory',
            ],
          },
          authorityTier: {
            enum: [
              'developer-ratification',
              'goal-charter',
              'ratified-contract',
              'coordinator-pattern',
              'parcel-spec',
              'standing-role',
              'generated-advisory',
            ],
          },
          authorityEffect: {
            enum: [
              'binding',
              'corroborating',
              'superseded-in-scope',
              'historical',
              'stale-explanation',
              'advisory-only',
            ],
          },
          scope: stringSet(['foreman-kernel', 'all-foreman-goals']),
          snapshotEvidence: {
            type: 'object',
            additionalProperties: false,
            required: ['commit', 'fullFileSha256'],
            properties: {
              commit: { type: 'string', pattern: '^[a-f0-9]{40}$' },
              fullFileSha256: sha256,
            },
          },
          inventoryItems: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              additionalProperties: false,
              required: [
                'itemId',
                'locator',
                'normalizedExcerpt',
                'valueDigest',
                'ruleIds',
                'exclusionDisposition',
                'rationale',
              ],
              properties: {
                itemId: id,
                locator: {
                  type: 'object',
                  additionalProperties: false,
                  required: ['kind', 'anchor'],
                  properties: {
                    kind: {
                      enum: [
                        'heading',
                        'numbered-item',
                        'table-row',
                        'symbol',
                        'line-excerpt',
                        'missing-path',
                      ],
                    },
                    anchor: { type: 'string', minLength: 1 },
                    lineHint: { type: 'integer', minimum: 1 },
                  },
                },
                normalizedExcerpt: { type: 'string', minLength: 1 },
                valueDigest: sha256,
                ruleIds: { type: 'array', items: id, uniqueItems: true },
                exclusionDisposition: {
                  enum: ['not-rule', 'duplicate-provenance', 'out-of-scope', null],
                },
                rationale: { type: 'string', minLength: 1 },
              },
            },
          },
        },
      },
    },
    rules: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'ruleId',
          'normalizedStatement',
          'sourceRefs',
          'applicability',
          'severity',
          'classification',
          'decision',
          'refusalCode',
          'enforcementOwner',
          'assurance',
          'pairedRuleIds',
          'retirementState',
          'retirementEvidence',
          'bindingDigest',
        ],
        properties: {
          ruleId: id,
          normalizedStatement: { type: 'string', minLength: 1 },
          sourceRefs: sourceRefArray,
          applicability: {
            type: 'object',
            additionalProperties: false,
            required: ['goals', 'roles', 'stages', 'operations', 'hosts'],
            properties: {
              goals: stringSet(['foreman-kernel', 'all-foreman-goals']),
              roles: stringSet([
                'developer',
                'coordinator',
                'shaper',
                'builder',
                'reviewer',
                'ci',
                'host-adapter',
                'kernel',
                'operator',
                'any',
              ]),
              stages: stringSet([
                'stage-zero',
                'shaping',
                'step-zero',
                'build',
                'deterministic-verify',
                'adversarial-review',
                'merge',
                'closure',
                'runtime',
                'any',
              ]),
              operations: stringSet([
                'source-inventory',
                'spec-mutation',
                'repo-read',
                'repo-mutation',
                'state-transition',
                'control-call',
                'receipt-validation',
                'external-write',
                'any',
              ]),
              hosts: stringSet([
                'provider-neutral',
                'claude-windows-docker-loaded',
                'claude-windows-docker-unenrolled',
                'unsupported-host',
                'ci',
                'any',
              ]),
            },
          },
          severity: { enum: ['info', 'low', 'medium', 'high', 'critical'] },
          classification: {
            enum: [
              'pre-action-refusal',
              'post-action-detection',
              'ci-static-check',
              'independent-review-human-judgment',
              'narrative-provenance',
              'unsupported',
            ],
          },
          decision: { enum: ['ALLOW', 'REFUSE', 'ADVISORY', 'CONFLICT', 'REQUIRE_HUMAN'] },
          refusalCode: { type: ['string', 'null'], pattern: '^[A-Z][A-Z0-9_]*$' },
          enforcementOwner: {
            enum: [
              'human-developer',
              'human-merge-operator',
              'coordinator',
              'kernel-policy',
              'host-adapter',
              'ci',
              'independent-reviewer',
              'provenance-only',
              'none',
            ],
          },
          assurance: {
            enum: [
              'narrative',
              'structural',
              'detected',
              'mediated',
              'independently-verified',
              'human-ratified',
            ],
          },
          pairedRuleIds: { type: 'array', items: id, uniqueItems: true },
          retirementState: {
            enum: [
              'active-reading',
              'required-backstop',
              'candidate-for-retirement',
              'retired-from-agent-reading',
              'historical-only',
            ],
          },
          retirementEvidence: {
            type: 'object',
            additionalProperties: false,
            required: [
              'predicate',
              'negativeRefusalTest',
              'corpusSweep',
              'independentBypassAttempt',
            ],
            properties: {
              predicate: { anyOf: [evidenceRefSchema, { type: 'null' }] },
              negativeRefusalTest: { anyOf: [evidenceRefSchema, { type: 'null' }] },
              corpusSweep: { anyOf: [evidenceRefSchema, { type: 'null' }] },
              independentBypassAttempt: { anyOf: [evidenceRefSchema, { type: 'null' }] },
            },
          },
          bindingDigest: sha256,
        },
      },
    },
    operationAuthority: {
      type: 'array',
      minItems: 7,
      maxItems: 7,
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'operationId',
          'allowedPrincipals',
          'requiredGitEvidence',
          'missingEvidenceDecision',
          'agentCallable',
          'operationalStateMaySatisfy',
          'toolMayIssueAuthorityEvidence',
        ],
        properties: {
          operationId: {
            enum: [
              'gate1.ratify',
              'gate2.dispatch',
              'gate3.merge',
              'verification.issue',
              'closure.record',
              'receipt.mint-generic',
              'external.write',
            ],
          },
          allowedPrincipals: {
            type: 'array',
            items: {
              enum: [
                'anonymous-read',
                'human-developer',
                'coordinator',
                'shaper',
                'builder',
                'independent-reviewer',
                'ci-service',
                'host-adapter',
                'kernel-operator',
              ],
            },
            uniqueItems: true,
          },
          requiredGitEvidence: { type: 'array', items: sourceRefSchema, uniqueItems: true },
          missingEvidenceDecision: { enum: ['REFUSE', 'CONFLICT', 'REQUIRE_HUMAN'] },
          agentCallable: { type: 'boolean' },
          operationalStateMaySatisfy: { type: 'boolean' },
          toolMayIssueAuthorityEvidence: { type: 'boolean' },
        },
      },
    },
    reconciliations: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'reconciliationId',
          'topic',
          'observedRefs',
          'observedEvidence',
          'authoritativeRuleIds',
          'scopedDisposition',
          'unresolvedConsequence',
          'migrationStatus',
          'supersedingEvidence',
        ],
        properties: {
          reconciliationId: id,
          topic: { type: 'string', minLength: 1 },
          observedRefs: sourceRefArray,
          observedEvidence: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['kind', 'reference', 'digest'],
              properties: {
                kind: { enum: ['source-ref', 'git-commit', 'command-result', 'missing-path'] },
                reference: { type: 'string', minLength: 1 },
                digest: sha256,
              },
            },
          },
          authoritativeRuleIds: { type: 'array', items: id, minItems: 1, uniqueItems: true },
          scopedDisposition: { type: 'string', minLength: 1 },
          unresolvedConsequence: { type: 'string', minLength: 1 },
          migrationStatus: {
            enum: ['open', 'resolved-for-fk', 'superseded-by-amendment', 'blocked'],
          },
          supersedingEvidence: nullableSourceRef,
        },
      },
    },
  },
}
