/**
 * `@foreman-line/kernel-state` — FK-P9 SQLite storage substrate and versioned
 * transactional migration ABI. Substrate, not policy: tables, constraints,
 * guarded writes, asserted WAL/busy policy, fail-closed refusals in the closed
 * `StorageErrorCode` registry, online backup/checkpoint, and byte-deterministic
 * storage exports. No lease, CAS, idempotency, transition, or projection logic.
 */

export {
  type BackupManifest,
  type BackupManifestProvenance,
  type BackupOptions,
  type BackupSink,
  backupManifestPathFor,
  backupTo,
  type PrunePolicy,
  pruneBackups,
  type VerifyBackupResult,
  verifyBackup,
} from './backup.js'
export {
  API_VERSION,
  type Digest,
  isDigestLiteral,
  STORAGE_DIGEST_DOMAINS,
} from './canonical.js'
export { type Clock, fixedClock, systemClock } from './clock.js'
export {
  CONSTRAINT_REASONS,
  type ConstraintReason,
  DRIVER_CODE_LITERALS,
  type DriverCodeLiteral,
  PATH_REFUSAL_REASONS,
  type PathRefusalReason,
  STORAGE_ERROR_CODE_COUNT,
  STORAGE_ERROR_CODES,
  STORAGE_ERROR_REGISTRY,
  StorageError,
  type StorageErrorCode,
  type StorageErrorDiagnostics,
  storageError,
} from './errors.js'
export {
  type ExportDocument,
  type ExportOptions,
  type ExportPayload,
  type ExportProvenance,
  type ExportRow,
  type ExportSink,
  exportStorage,
  type StorageExport,
  storageExportDigestOf,
} from './export.js'
export {
  type BackupPolicy,
  BUSY_TIMEOUT_DEFAULT_MICROS,
  type CheckpointMode,
  checkpoint,
  closeStorage,
  type OpenStorageConfig,
  openStorage,
  type RetentionDescriptor,
  storagePathFor,
  type VerifyResult,
  verifyStorage,
  WAL_AUTOCHECKPOINT_PAGES,
} from './open.js'
export {
  type ArtifactRow,
  consumeWakeupHandoff,
  type EventQuery,
  type EventRow,
  type GoalRow,
  type GoalUpdate,
  getGoal,
  getIdempotencyKey,
  getLease,
  getProjectionCursor,
  getTransition,
  getUnreleasedLease,
  type IdempotencyKeyLookup,
  type IdempotencyKeyRow,
  insertArtifact,
  insertEvent,
  insertGoal,
  insertIdempotencyKey,
  insertLease,
  insertTransition,
  insertWakeupHandoff,
  type LeaseRow,
  type LeaseUpdate,
  type NewArtifactRow,
  type NewEventRow,
  type NewGoalRow,
  type NewIdempotencyKeyRow,
  type NewLeaseRow,
  type NewTransitionRow,
  type NewWakeupHandoffRow,
  type ProjectionCursorRow,
  queryEvents,
  type SchemaMigrationRow,
  type SetProjectionCursorRow,
  setProjectionCursor,
  type TransitionRow,
  type TransitionUpdate,
  updateGoalRow,
  updateLeaseRow,
  updateTransitionRow,
  type WakeupHandoffRow,
} from './rows.js'
export {
  ARTIFACT_LOCATOR_MAX_BYTES,
  EVENT_PAYLOAD_MAX_BYTES,
  isDigest,
  isId,
  isSafeInt,
  SUBSTRATE_TABLES,
  TABLE_KEY_TUPLES,
  WAKEUP_KINDS,
  type WakeupKind,
} from './schema.js'
export { type Storage, withTransaction } from './transactions.js'
