$dir = Split-Path -Parent $MyInvocation.MyCommand.Path
$common = 'Read brief.md in the current directory and complete the task in its Your task section. Return ONLY the exact output contract in brief.md, plain text, max 350 words.'
$jobs = @()
$jobs += Start-Process -FilePath 'C:\Users\clint\.grok\bin\grok.exe' -WorkingDirectory $dir -ArgumentList @('--always-approve','-p',"Architecture failure-mode auditor. Judge provider boundaries, routing failure modes, and Foreman governance hardest. $common") -RedirectStandardOutput (Join-Path $dir 'grok-out.txt') -RedirectStandardError (Join-Path $dir 'grok-err.txt') -PassThru
$jobs += Start-Process -FilePath 'powershell.exe' -WorkingDirectory $dir -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File','D:\nodejs_symlinks\codex.ps1','exec','--skip-git-repo-check',"Operational mechanics auditor. Judge correctness, integration contracts, observability, and rollout acceptance criteria hardest. $common") -RedirectStandardOutput (Join-Path $dir 'codex-out.txt') -RedirectStandardError (Join-Path $dir 'codex-err.txt') -PassThru
$env:ANTHROPIC_BASE_URL = $null
$jobs += Start-Process -FilePath 'powershell.exe' -WorkingDirectory $dir -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File','D:\nodejs_symlinks\claude.ps1','-p',"Governance consistency auditor. Judge whether routing contradicts role, approval, risk, and evidence boundaries hardest. $common",'--allowedTools','Read,Write') -RedirectStandardOutput (Join-Path $dir 'claude-out.txt') -RedirectStandardError (Join-Path $dir 'claude-err.txt') -PassThru
$jobs += Start-Process -FilePath 'D:\nodejs_symlinks\node.exe' -WorkingDirectory $dir -ArgumentList @('D:\nodejs_symlinks\node_modules\@google\gemini-cli\bundle\gemini.js','-p',"Cost and quality auditor. Judge tier design, model/provider fit, thinking levels, and economic tradeoffs hardest. $common") -RedirectStandardOutput (Join-Path $dir 'gemini-out.txt') -RedirectStandardError (Join-Path $dir 'gemini-err.txt') -PassThru
$jobs | Select-Object Id,ProcessName | Out-File -Encoding utf8 (Join-Path $dir 'council-processes.txt')
