/**
 * F9 projection-output injection (#31): the deterministic `sanitizeForMarkdown`
 * pin (T6 rule 4) replayed over the hostile fixture with golden bytes, plus the
 * linear-time bound (#19) over a hostile multi-megabyte spray.
 *
 * Derivation discipline: the golden/scan tests derive FROM the fixture rows;
 * the INJ-01..INJ-07 id enum is generated by range join — no hand-typed total
 * literal appears anywhere.
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'
import { sanitizeForMarkdown } from '../src/sanitize.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const LF = String.fromCharCode(10)
const UFFFD = String.fromCodePoint(0xfffd)

interface InjectionRow {
  id: string
  input: { value: string }
  expectedOutcome: string
  expectedSanitized: string
}

const FIXTURE = JSON.parse(
  readFileSync(join(HERE, 'fixtures', 'hostile', 'injection.json'), 'utf8'),
) as { class: string; records: InjectionRow[] }
const ROWS = FIXTURE.records

/** The declared F9 id enum INJ-01..INJ-07, generated by range join. */
const EXPECTED_INJ_IDS = Array.from(
  { length: 7 },
  (_, index) => `INJ-${String(index + 1).padStart(2, '0')}`,
)

function assertNoControlFormatOrSurrogate(value: string): void {
  for (let i = 0; i < value.length; i += 1) {
    const unit = value.charCodeAt(i)
    assert.ok(unit > 0x1f && unit !== 0x7f, `control byte at ${i} of ${JSON.stringify(value)}`)
    assert.ok(
      unit !== 0x200b &&
        unit !== 0x200e &&
        unit !== 0x200f &&
        !(unit >= 0x202a && unit <= 0x202e) &&
        unit !== 0xfeff,
      `format byte at ${i} of ${JSON.stringify(value)}`,
    )
    if (unit >= 0xd800 && unit <= 0xdbff) {
      const next = i + 1 < value.length ? value.charCodeAt(i + 1) : 0
      assert.ok(next >= 0xdc00 && next <= 0xdfff, `lone high surrogate at ${i}`)
      i += 1
    } else if (unit >= 0xdc00 && unit <= 0xdfff) {
      assert.fail(`lone low surrogate at ${i}`)
    }
  }
}

// --- fixture inventory (derived, never hand-typed) -------------------------

test('fixture inventory: F9 rows are exactly the declared INJ id enum', () => {
  assert.equal(FIXTURE.class, 'F9')
  const ids = ROWS.map((row) => row.id)
  assert.equal(new Set(ids).size, ids.length, 'duplicate row ids')
  assert.equal(ROWS.length, EXPECTED_INJ_IDS.length)
  assert.deepEqual([...ids].sort(), [...EXPECTED_INJ_IDS].sort())
  for (const row of ROWS) {
    assert.equal(row.expectedOutcome, 'sanitized')
    assert.equal(typeof row.input.value, 'string')
    assert.equal(typeof row.expectedSanitized, 'string')
  }
})

// --- golden bytes + scan, one test per fixture row -------------------------

for (const row of ROWS) {
  test(`golden bytes: ${row.id} sanitizes to its pre-declared form`, () => {
    assert.equal(sanitizeForMarkdown(row.input.value), row.expectedSanitized)
  })

  test(`scan: ${row.id} output carries no control/format byte or unpaired surrogate`, () => {
    assertNoControlFormatOrSurrogate(sanitizeForMarkdown(row.input.value))
    assertNoControlFormatOrSurrogate(row.expectedSanitized)
  })
}

// --- structural-escape proofs ---------------------------------------------

test('structural: a sanitized pipe cannot break a Markdown table row', () => {
  const cell = sanitizeForMarkdown('a | b | c')
  assert.equal(cell, 'a \\| b \\| c')
  for (let i = 0; i < cell.length; i += 1) {
    if (cell.charCodeAt(i) === 0x7c) {
      assert.equal(cell.charCodeAt(i - 1), 0x5c, `raw pipe at ${i}`)
    }
  }
})

test('structural: a sanitized backtick run cannot open or close a fence', () => {
  const out = sanitizeForMarkdown('```' + LF + 'runaway' + LF + '```')
  assert.equal(out, '\\`\\`\\` runaway \\`\\`\\`')
  for (let i = 0; i < out.length; i += 1) {
    if (out.charCodeAt(i) === 0x60) {
      assert.equal(out.charCodeAt(i - 1), 0x5c, `raw backtick at ${i}`)
    }
  }
  assert.ok(!out.includes(LF), 'a fence needs a line start')
})

test('structural: leading #/-/digit-dot cannot create a heading or list', () => {
  assert.equal(sanitizeForMarkdown('# heading'), '\\# heading')
  assert.equal(sanitizeForMarkdown('- list item'), '\\- list item')
  assert.equal(sanitizeForMarkdown('1. step'), '1\\. step')
  assert.equal(sanitizeForMarkdown('42. step'), '42\\. step')
})

test('structural: a leading > is escaped exactly once (never double-escaped)', () => {
  assert.equal(sanitizeForMarkdown('> quote'), '\\> quote')
})

test('structural: an HTML-ish payload cannot open HTML', () => {
  const out = sanitizeForMarkdown('<script>alert(1)</script>')
  assert.equal(out, '\\<script\\>alert(1)\\</script\\>')
  for (let i = 0; i < out.length; i += 1) {
    const unit = out.charCodeAt(i)
    if (unit === 0x3c || unit === 0x3e) {
      assert.equal(out.charCodeAt(i - 1), 0x5c, `raw angle bracket at ${i}`)
    }
  }
})

// --- byte-for-byte pass-through discipline ---------------------------------

test('the empty string is identity', () => {
  assert.equal(sanitizeForMarkdown(''), '')
})

test('pure printable ASCII passes through byte-for-byte', () => {
  const ascii = 'goal-42 /path/to/file.md [P0] (owner: ops) 0..9'
  assert.equal(sanitizeForMarkdown(ascii), ascii)
})

test('Unicode passes byte-for-byte: no normalization, no case folding', () => {
  const combining = String.fromCharCode(0x301)
  const composed = String.fromCodePoint(0xe9)
  assert.equal(sanitizeForMarkdown('cafe' + combining), 'cafe' + combining)
  assert.equal(sanitizeForMarkdown('caf' + composed), 'caf' + composed)
  assert.notEqual('cafe' + combining, 'caf' + composed)
  assert.equal(sanitizeForMarkdown('MiXeD Case'), 'MiXeD Case')
})

test('unpaired surrogates become U+FFFD; pairs pass byte-for-byte; total', () => {
  const loneHigh = String.fromCharCode(0xd800)
  const loneLow = String.fromCharCode(0xdc00)
  const pair = String.fromCharCode(0xd83d, 0xde00)
  const highLowPair = String.fromCharCode(0xd800, 0xdc00)
  assert.equal(sanitizeForMarkdown(loneHigh), UFFFD)
  assert.equal(sanitizeForMarkdown(loneLow), UFFFD)
  assert.equal(sanitizeForMarkdown(loneHigh + loneHigh), UFFFD + UFFFD)
  assert.equal(sanitizeForMarkdown(loneHigh + 'x'), UFFFD + 'x')
  assert.equal(sanitizeForMarkdown(pair), pair)
  assert.equal(sanitizeForMarkdown(highLowPair), highLowPair)
  assert.doesNotThrow(() => sanitizeForMarkdown(loneHigh + loneLow + loneLow))
  assert.equal(sanitizeForMarkdown(loneHigh + loneLow + loneLow), highLowPair + UFFFD)
})

// --- linear-time bound pin (#19) -------------------------------------------

const SPRAY_UNIT = String.fromCodePoint(
  0x60,
  0x7c,
  0x202e,
  0x3c,
  0xd,
  0xa,
  0x3e,
  0x200b,
  0x0,
  0x23,
  0x2d,
  0x31,
  0x2e,
)
const SPRAY_256K = SPRAY_UNIT.repeat(Math.ceil((256 * 1024) / SPRAY_UNIT.length))
const SPRAY_4M = SPRAY_UNIT.repeat(Math.ceil((4 * 1024 * 1024) / SPRAY_UNIT.length))

function elapsedSanitize(input: string): number {
  const started = performance.now()
  const out = sanitizeForMarkdown(input)
  assert.ok(out.length > 0, 'sanitizer produced no output')
  return performance.now() - started
}

test('linear-time bound (#19): hostile ~4 MiB spray sanitizes within 5 s', () => {
  sanitizeForMarkdown(SPRAY_256K)
  sanitizeForMarkdown(SPRAY_4M)
  const elapsedMs = elapsedSanitize(SPRAY_4M)
  assert.ok(elapsedMs < 5000, `4 MiB hostile spray took ${elapsedMs.toFixed(1)}ms`)
})

test('linear-time scaling (#19): 16x input size stays far below quadratic cost', () => {
  sanitizeForMarkdown(SPRAY_256K)
  sanitizeForMarkdown(SPRAY_4M)
  let smallMs = Number.POSITIVE_INFINITY
  let largeMs = Number.POSITIVE_INFINITY
  // Interleaved measurement order: scheduling phases hit both sizes equally, so
  // the min-of-9 ratio stays stable under imposed load (flakes-are-failures).
  for (let run = 0; run < 9; run += 1) {
    if (run % 2 === 0) {
      smallMs = Math.min(smallMs, elapsedSanitize(SPRAY_256K))
      largeMs = Math.min(largeMs, elapsedSanitize(SPRAY_4M))
    } else {
      largeMs = Math.min(largeMs, elapsedSanitize(SPRAY_4M))
      smallMs = Math.min(smallMs, elapsedSanitize(SPRAY_256K))
    }
  }
  // 0.5 ms floor keeps timer granularity from dominating the small measurement.
  // Bound discrimination: linear scaling costs 16x, quadratic would cost 256x —
  // 64x excludes any super-linear blowup with margin on both sides while
  // tolerating scheduler noise in the small measurement.
  const ratio = largeMs / Math.max(smallMs, 0.5)
  assert.ok(
    ratio < 64,
    `16x size cost ${ratio.toFixed(1)}x time (small ${smallMs.toFixed(1)}ms, large ${largeMs.toFixed(1)}ms)`,
  )
})
